baseURL: 'https://blog.wssh.trade/'
languageCode: 'en-us'
title: "Wong's Blog"
theme: PaperMod

# googleAnalytics: G-JL04FF8DWE

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
hasCJKLanguage: true
pagerSize: 5

enableInlineShortcodes: true

minify:
  disableXML: true
  minifyOutput: true 

outputs:
    home:
        - HTML
        - RSS
        - JSON

menu:
    main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10

params:
  env: production
  title: Wong's Blog
  description: A blog about python, JavaScript, front-end, web3 and back-end
  keywords: [python, javascript, front-end, back-end, web3, blockchain]
  author: WongSSH
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true

  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  homeInfoParams:
      Title: "WongSSH's Blog"
      Content: >
          - Welcome to my blog.

          - You can find web3, smart contract, golang, python and many other interesting contents
          
  socialIcons:
      - name: github
        url: "https://github.com/wangshouh"
      - name: Rss
        url: "index.xml"
      - name: Email
        url: "mailto:wongshouhao@outlook.com"
      - name: Telegram
        url: "https://t.me/web3list"
      - name: Twitter
        url: "https://twitter.com/wong_ssh"
